name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - run: corepack enable
          - uses: actions/setup-node@v3
            with:
              node-version: "16"
              cache: "pnpm"

          - name: Install dependencies
            run: pnpm install --frozen-lockfile

          - name: Run unit tests
            run: pnpm test:unit

    e2e:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/playwright:v1.30.0-focal

        steps:
            - uses: actions/checkout@v3
            - run: corepack enable
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - run: pnpm test:e2e

    lint:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - run: corepack enable
          - uses: actions/setup-node@v3
            with:
              node-version: "16"
              cache: "pnpm"

          - name: Install dependencies
            run: pnpm install --frozen-lockfile

          - name: Lint
            run: pnpm lint
